@echo off
echo Starting CapaRox Trading Bot...
echo Starting API Server...
start "CapaRox API" python api/index.py
echo Starting Bot Worker...
start "CapaRox Worker" python worker.py
echo Deployment Complete. Check the opened windows for logs.
pause
